var pokemonList = [
{id:"001", name:"Bulbasaur", type:"Grass", type2:"Poison",},
{id:"002", name:"Ivysaur", type:"Grass", type2:"Poison",},
{id:"003", name:"Venusaur", type:"Grass", type2:"Poison",},
{id:"004", name:"Charmander", type:"Fire", type2:"None",},
{id:"005", name:"Charmeleon", type:"Fire", type2:"None",},
{id:"006", name:"Charizard", type:"Fire", type2:"Flying",},
{id:"007", name:"Squirtle", type:"Water", type2:"None",},
{id:"008", name:"Wartortle", type:"Water", type2:"None",},
{id:"009", name:"Blastoise", type:"Water", type2:"None",},
{id:"010", name:"Caterpie", type:"Bug", type2:"None",},
{id:"011", name:"Metapod", type:"Bug", type2:"None",},
{id:"012", name:"Butterfree", type:"Bug", type2:"Flying",},
{id:"013", name:"Weedle", type:"Bug", type2:"Poison",},
{id:"014", name:"Kakuna", type:"Bug", type2:"Poison",},
{id:"015", name:"Beedrill", type:"Bug", type2:"Poison",},
{id:"016", name:"Pidgey", type:"Normal", type2:"Flying",},
{id:"017", name:"Pidgeotto", type:"Normal", type2:"Flying",},
{id:"018", name:"Pidgeot", type:"Normal", type2:"Flying",},
{id:"019", name:"Rattata", type:"Normal", type2:"None",},
{id:"020", name:"Raticate", type:"Normal", type2:"None",},
{id:"021", name:"Spearow", type:"Normal", type2:"Flying",},
{id:"022", name:"Fearow", type:"Normal", type2:"Flying",},
{id:"023", name:"Ekans", type:"Poison", type2:"None",},
{id:"024", name:"Arbok", type:"Poison", type2:"None",},
{id:"025", name:"Pikachu", type:"Electric", type2:"None",},
{id:"026", name:"Raichu", type:"Electric", type2:"None",},
{id:"027", name:"Sandshrew", type:"Ground", type2:"None",},
{id:"028", name:"Sandslash", type:"Ground", type2:"None",},
{id:"029", name:"Nidoran♀", type:"Poison", type2:"None",},
{id:"030", name:"Nidorina", type:"Poison", type2:"None",},
{id:"031", name:"Nidoqueen", type:"Poison", type2:"Ground",},
{id:"032", name:"Nidoran♂", type:"Poison", type2:"None",},
{id:"033", name:"Nidorino", type:"Poison", type2:"None",},
{id:"034", name:"Nidoking", type:"Poison", type2:"Ground",},
{id:"035", name:"Clefairy", type:"Fairy", type2:"None",},
{id:"036", name:"Clefable", type:"Fairy", type2:"None",},
{id:"037", name:"Vulpix", type:"Fire", type2:"None",},
{id:"038", name:"Ninetales", type:"Fire", type2:"None",},
{id:"039", name:"Jigglypuff", type:"Normal", type2:"Fairy",},
{id:"040", name:"Wigglytuff", type:"Normal", type2:"Fairy",},
{id:"041", name:"Zubat", type:"Poison", type2:"Flying",},
{id:"042", name:"Golbat", type:"Poison", type2:"Flying",},
{id:"043", name:"Oddish", type:"Grass", type2:"Poison",},
{id:"044", name:"Gloom", type:"Grass", type2:"Poison",},
{id:"045", name:"Vileplume", type:"Grass", type2:"Poison",},
{id:"046", name:"Paras", type:"Bug", type2:"Grass",},
{id:"047", name:"Parasect", type:"Bug", type2:"Grass",},
{id:"048", name:"Venonat", type:"Bug", type2:"Poison",},
{id:"049", name:"Venomoth", type:"Bug", type2:"Poison",},
{id:"050", name:"Diglett", type:"Ground", type2:"None",},
{id:"051", name:"Dugtrio", type:"Ground", type2:"None",},
{id:"052", name:"Meowth", type:"Normal", type2:"None",},
{id:"053", name:"Persian", type:"Normal", type2:"None",},
{id:"054", name:"Psyduck", type:"Water", type2:"None",},
{id:"055", name:"Golduck", type:"Water", type2:"None",},
{id:"056", name:"Mankey", type:"Fighting", type2:"None",},
{id:"057", name:"Primeape", type:"Fighting", type2:"None",},
{id:"058", name:"Growlithe", type:"Fire", type2:"None",},
{id:"059", name:"Arcanine", type:"Fire", type2:"None",},
{id:"060", name:"Poliwag", type:"Water", type2:"None",},
{id:"061", name:"Poliwhirl", type:"Water", type2:"None",},
{id:"062", name:"Poliwrath", type:"Water", type2:"Fighting",},
{id:"063", name:"Abra", type:"Psychic", type2:"None",},
{id:"064", name:"Kadabra", type:"Psychic", type2:"None",},
{id:"065", name:"Alakazam", type:"Psychic", type2:"None",},
{id:"066", name:"Machop", type:"Fighting", type2:"None",},
{id:"067", name:"Machoke", type:"Fighting", type2:"None",},
{id:"068", name:"Machamp", type:"Fighting", type2:"None",},
{id:"069", name:"Bellsprout", type:"Grass", type2:"Poison",},
{id:"070", name:"Weepinbell", type:"Grass", type2:"Poison",},
{id:"071", name:"Victreebel", type:"Grass", type2:"Poison",},
{id:"072", name:"Tentacool", type:"Water", type2:"Poison",},
{id:"073", name:"Tentacruel", type:"Water", type2:"Poison",},
{id:"074", name:"Geodude", type:"Rock", type2:"Ground",},
{id:"075", name:"Graveler", type:"Rock", type2:"Ground",},
{id:"076", name:"Golem", type:"Rock", type2:"Ground",},
{id:"077", name:"Ponyta", type:"Fire", type2:"None",},
{id:"078", name:"Rapidash", type:"Fire", type2:"None",},
{id:"079", name:"Slowpoke", type:"Water", type2:"Psychic",},
{id:"080", name:"Slowbro", type:"Water", type2:"Psychic",},
{id:"081", name:"Magnemite", type:"Electric", type2:"Steel",},
{id:"082", name:"Magneton", type:"Electric", type2:"Steel",},
{id:"083", name:"Farfetch'd", type:"Normal", type2:"Flying",},
{id:"084", name:"Doduo", type:"Normal", type2:"Flying",},
{id:"085", name:"Dodrio", type:"Normal", type2:"Flying",},
{id:"086", name:"Seel", type:"Water", type2:"None",},
{id:"087", name:"Dewgong", type:"Water", type2:"Ice",},
{id:"088", name:"Grimer", type:"Poison", type2:"None",},
{id:"089", name:"Muk", type:"Poison", type2:"None",},
{id:"090", name:"Shellder", type:"Water", type2:"None",},
{id:"091", name:"Cloyster", type:"Water", type2:"Ice",},
{id:"092", name:"Gastly", type:"Ghost", type2:"Poison",},
{id:"093", name:"Haunter", type:"Ghost", type2:"Poison",},
{id:"094", name:"Gengar", type:"Ghost", type2:"Poison",},
{id:"095", name:"Onix", type:"Rock", type2:"Ground",},
{id:"096", name:"Drowzee", type:"Psychic", type2:"None",},
{id:"097", name:"Hypno", type:"Psychic", type2:"None",},
{id:"098", name:"Krabby", type:"Water", type2:"None",},
{id:"099", name:"Kingler", type:"Water", type2:"None",},
{id:"100", name:"Voltorb", type:"Electric", type2:"None",},
{id:"101", name:"Electrode", type:"Electric", type2:"None",},
{id:"102", name:"Exeggcute", type:"Grass", type2:"Psychic",},
{id:"103", name:"Exeggutor", type:"Grass", type2:"Psychic",},
{id:"104", name:"Cubone", type:"Ground", type2:"None",},
{id:"105", name:"Marowak", type:"Ground", type2:"None",},
{id:"106", name:"Hitmonlee", type:"Fighting", type2:"None",},
{id:"107", name:"Hitmonchan", type:"Fighting", type2:"None",},
{id:"108", name:"Lickitung", type:"Normal", type2:"None",},
{id:"109", name:"Koffing", type:"Poison", type2:"None",},
{id:"110", name:"Weezing", type:"Poison", type2:"None",},
{id:"111", name:"Rhyhorn", type:"Ground", type2:"Rock",},
{id:"112", name:"Rhydon", type:"Ground", type2:"Rock",},
{id:"113", name:"Chansey", type:"Normal", type2:"None",},
{id:"114", name:"Tangela", type:"Grass", type2:"None",},
{id:"115", name:"Kangaskhan", type:"Normal", type2:"None",},
{id:"116", name:"Horsea", type:"Water", type2:"None",},
{id:"117", name:"Seadra", type:"Water", type2:"None",},
{id:"118", name:"Goldeen", type:"Water", type2:"None",},
{id:"119", name:"Seaking", type:"Water", type2:"None",},
{id:"120", name:"Staryu", type:"Water", type2:"None",},
{id:"121", name:"Starmie", type:"Water", type2:"Psychic",},
{id:"122", name:"Mr. Mime", type:"Psychic", type2:"Fairy",},
{id:"123", name:"Scyther", type:"Bug", type2:"Flying",},
{id:"124", name:"Jynx", type:"Ice", type2:"Psychic",},
{id:"125", name:"Electabuzz", type:"Electric", type2:"None",},
{id:"126", name:"Magmar", type:"Fire", type2:"None",},
{id:"127", name:"Pinsir", type:"Bug", type2:"None",},
{id:"128", name:"Tauros", type:"Normal", type2:"None",},
{id:"129", name:"Magikarp", type:"Water", type2:"None",},
{id:"130", name:"Gyarados", type:"Water", type2:"Flying",},
{id:"131", name:"Lapras", type:"Water", type2:"Ice",},
{id:"132", name:"Ditto", type:"Normal", type2:"None",},
{id:"133", name:"Eevee", type:"Normal", type2:"None",},
{id:"134", name:"Vaporeon", type:"Water", type2:"None",},
{id:"135", name:"Jolteon", type:"Electric", type2:"None",},
{id:"136", name:"Flareon", type:"Fire", type2:"None",},
{id:"137", name:"Porygon", type:"Normal", type2:"None",},
{id:"138", name:"Omanyte", type:"Rock", type2:"Water",},
{id:"139", name:"Omastar", type:"Rock", type2:"Water",},
{id:"140", name:"Kabuto", type:"Rock", type2:"Water",},
{id:"141", name:"Kabutops", type:"Rock", type2:"Water",},
{id:"142", name:"Aerodactyl", type:"Rock", type2:"Flying",},
{id:"143", name:"Snorlax", type:"Normal", type2:"None",},
{id:"144", name:"Articuno", type:"Ice", type2:"Flying",},
{id:"145", name:"Zapdos", type:"Electric", type2:"Flying",},
{id:"146", name:"Moltres", type:"Fire", type2:"Flying",},
{id:"147", name:"Dratini", type:"Dragon", type2:"None",},
{id:"148", name:"Dragonair", type:"Dragon", type2:"None",},
{id:"149", name:"Dragonite", type:"Dragon", type2:"Flying",},
{id:"150", name:"Mewtwo", type:"Psychic", type2:"None",},
{id:"151", name:"Mew", type:"Psychic", type2:"None",},
{id:"152", name:"Chikorita", type:"Grass", type2:"None",},
{id:"153", name:"Bayleef", type:"Grass", type2:"None",},
{id:"154", name:"Meganium", type:"Grass", type2:"None",},
{id:"155", name:"Cyndaquil", type:"Fire", type2:"None",},
{id:"156", name:"Quilava", type:"Fire", type2:"None",},
{id:"157", name:"Typhlosion", type:"Fire", type2:"None",},
{id:"158", name:"Totodile", type:"Water", type2:"None",},
{id:"159", name:"Croconaw", type:"Water", type2:"None",},
{id:"160", name:"Feraligatr", type:"Water", type2:"None",},
{id:"161", name:"Sentret", type:"Normal", type2:"None",},
{id:"162", name:"Furret", type:"Normal", type2:"None",},
{id:"163", name:"Hoothoot", type:"Normal", type2:"Flying",},
{id:"164", name:"Noctowl", type:"Normal", type2:"Flying",},
{id:"165", name:"Ledyba", type:"Bug", type2:"Flying",},
{id:"166", name:"Ledian", type:"Bug", type2:"Flying",},
{id:"167", name:"Spinarak", type:"Bug", type2:"Poison",},
{id:"168", name:"Ariados", type:"Bug", type2:"Poison",},
{id:"169", name:"Crobat", type:"Poison", type2:"Flying",},
{id:"170", name:"Chinchou", type:"Water", type2:"Electric",},
{id:"171", name:"Lanturn", type:"Water", type2:"Electric",},
{id:"172", name:"Pichu", type:"Electric", type2:"None",},
{id:"173", name:"Cleffa", type:"Fairy", type2:"None",},
{id:"174", name:"Igglybuff", type:"Normal", type2:"Fairy",},
{id:"175", name:"Togepi", type:"Fairy", type2:"None",},
{id:"176", name:"Togetic", type:"Flying", type2:"None",},
{id:"177", name:"Natu", type:"Psychic", type2:"Flying",},
{id:"178", name:"Xatu", type:"Psychic", type2:"Flying",},
{id:"179", name:"Mareep", type:"Electric", type2:"None",},
{id:"180", name:"Flaaffy", type:"Electric", type2:"None",},
{id:"181", name:"Ampharos", type:"Electric", type2:"None",},
{id:"182", name:"Bellossom", type:"Grass", type2:"None",},
{id:"183", name:"Marill", type:"Water", type2:"Fairy",},
{id:"184", name:"Azumarill", type:"Water", type2:"Fairy",},
{id:"185", name:"Sudowoodo", type:"Rock", type2:"None",},
{id:"186", name:"Politoed", type:"Water", type2:"None",},
{id:"187", name:"Hoppip", type:"Grass", type2:"Flying",},
{id:"188", name:"Skiploom", type:"Grass", type2:"Flying",},
{id:"189", name:"Jumpluff", type:"Grass", type2:"Flying",},
{id:"190", name:"Aipom", type:"Normal", type2:"None",},
{id:"191", name:"Sunkern", type:"Grass", type2:"None",},
{id:"192", name:"Sunflora", type:"Grass", type2:"None",},
{id:"193", name:"Yanma", type:"Bug", type2:"Flying",},
{id:"194", name:"Wooper", type:"Water", type2:"Ground",},
{id:"195", name:"Quagsire", type:"Water", type2:"Ground",},
{id:"196", name:"Espeon", type:"Psychic", type2:"None",},
{id:"197", name:"Umbreon", type:"Dark", type2:"None",},
{id:"198", name:"Murkrow", type:"Dark", type2:"Flying",},
{id:"199", name:"Slowking", type:"Water", type2:"Psychic",},
{id:"200", name:"Misdreavus", type:"Ghost", type2:"None",},
{id:"201", name:"Unown", type:"Psychic", type2:"None",},
{id:"202", name:"Wobbuffet", type:"Psychic", type2:"None",},
{id:"203", name:"Girafarig", type:"Normal", type2:"Psychic",},
{id:"204", name:"Pineco", type:"Bug", type2:"None",},
{id:"205", name:"Forretress", type:"Bug", type2:"Steel",},
{id:"206", name:"Dunsparce", type:"Normal", type2:"None",},
{id:"207", name:"Gligar", type:"Ground", type2:"Flying",},
{id:"208", name:"Steelix", type:"Steel", type2:"Ground",},
{id:"209", name:"Snubbull", type:"Fairy", type2:"None",},
{id:"210", name:"Granbull", type:"Fairy", type2:"None",},
{id:"211", name:"Qwilfish", type:"Water", type2:"Poison",},
{id:"212", name:"Scizor", type:"Bug", type2:"Steel",},
{id:"213", name:"Shuckle", type:"Bug", type2:"Rock",},
{id:"214", name:"Heracross", type:"Bug", type2:"Fighting",},
{id:"215", name:"Sneasel", type:"Dark", type2:"Ice",},
{id:"216", name:"Teddiursa", type:"Normal", type2:"None",},
{id:"217", name:"Ursaring", type:"Normal", type2:"None",},
{id:"218", name:"Slugma", type:"Fire", type2:"None",},
{id:"219", name:"Magcargo", type:"Fire", type2:"Rock",},
{id:"220", name:"Swinub", type:"Ice", type2:"Ground",},
{id:"221", name:"Piloswine", type:"Ice", type2:"Ground",},
{id:"222", name:"Corsola", type:"Water", type2:"Rock",},
{id:"223", name:"Remoraid", type:"Water", type2:"None",},
{id:"224", name:"Octillery", type:"Water", type2:"None",},
{id:"225", name:"Delibird", type:"Ice", type2:"Flying",},
{id:"226", name:"Mantine", type:"Water", type2:"Flying",},
{id:"227", name:"Skarmory", type:"Steel", type2:"Flying",},
{id:"228", name:"Houndour", type:"Dark", type2:"Fire",},
{id:"229", name:"Houndoom", type:"Dark", type2:"Fire",},
{id:"230", name:"Kingdra", type:"Water", type2:"Dragon",},
{id:"231", name:"Phanpy", type:"Ground", type2:"None",},
{id:"232", name:"Donphan", type:"Ground", type2:"None",},
{id:"233", name:"Porygon2", type:"Normal", type2:"None",},
{id:"234", name:"Stantler", type:"Normal", type2:"None",},
{id:"235", name:"Smeargle", type:"Normal", type2:"None",},
{id:"236", name:"Tyrogue", type:"Fighting", type2:"None",},
{id:"237", name:"Hitmontop", type:"Fighting", type2:"None",},
{id:"238", name:"Smoochum", type:"Ice", type2:"Psychic",},
{id:"239", name:"Elekid", type:"Electric", type2:"None",},
{id:"240", name:"Magby", type:"Fire", type2:"None",},
{id:"241", name:"Miltank", type:"Normal", type2:"None",},
{id:"242", name:"Blissey", type:"Normal", type2:"None",},
{id:"243", name:"Raikou", type:"Electric", type2:"None",},
{id:"244", name:"Entei", type:"Fire", type2:"None",},
{id:"245", name:"Suicune", type:"Water", type2:"None",},
{id:"246", name:"Larvitar", type:"Rock", type2:"Ground",},
{id:"247", name:"Pupitar", type:"Rock", type2:"Ground",},
{id:"248", name:"Tyranitar", type:"Rock", type2:"Dark",},
{id:"249", name:"Lugia", type:"Psychic", type2:"Flying",},
{id:"250", name:"Ho-Oh", type:"Fire", type2:"Flying",},
{id:"251", name:"Celebi", type:"Psychic", type2:"Grass",},
{id:"252", name:"Treecko", type:"Grass", type2:"None",},
{id:"253", name:"Grovyle", type:"Grass", type2:"None",},
{id:"254", name:"Sceptile", type:"Grass", type2:"None",},
{id:"255", name:"Torchic", type:"Fire", type2:"None",},
{id:"256", name:"Combusken", type:"Fire", type2:"Fighting",},
{id:"257", name:"Blaziken", type:"Fire", type2:"Fighting",},
{id:"258", name:"Mudkip", type:"Water", type2:"None",},
{id:"259", name:"Marshtomp", type:"Water", type2:"Ground",},
{id:"260", name:"Swampert", type:"Water", type2:"Ground",},
{id:"261", name:"Poochyena", type:"Dark", type2:"None",},
{id:"262", name:"Mightyena", type:"Dark", type2:"None",},
{id:"263", name:"Zigzagoon", type:"Normal", type2:"None",},
{id:"264", name:"Linoone", type:"Normal", type2:"None",},
{id:"265", name:"Wurmple", type:"Bug", type2:"None",},
{id:"266", name:"Silcoon", type:"Bug", type2:"None",},
{id:"267", name:"Beautifly", type:"Bug", type2:"Flying",},
{id:"268", name:"Cascoon", type:"Bug", type2:"None",},
{id:"269", name:"Dustox", type:"Bug", type2:"Poison",},
{id:"270", name:"Lotad", type:"Water", type2:"Grass",},
{id:"271", name:"Lombre", type:"Water", type2:"Grass",},
{id:"272", name:"Ludicolo", type:"Water", type2:"Grass",},
{id:"273", name:"Seedot", type:"Grass", type2:"None",},
{id:"274", name:"Nuzleaf", type:"Grass", type2:"Dark",},
{id:"275", name:"Shiftry", type:"Grass", type2:"Dark",},
{id:"276", name:"Taillow", type:"Normal", type2:"Flying",},
{id:"277", name:"Swellow", type:"Normal", type2:"Flying",},
{id:"278", name:"Wingull", type:"Water", type2:"Flying",},
{id:"279", name:"Pelipper", type:"Water", type2:"Flying",},
{id:"280", name:"Ralts", type:"Psychic", type2:"Fairy",},
{id:"281", name:"Kirlia", type:"Psychic", type2:"Fairy",},
{id:"282", name:"Gardevoir", type:"Psychic", type2:"Fairy",},
{id:"283", name:"Surskit", type:"Bug", type2:"Water",},
{id:"284", name:"Masquerain", type:"Bug", type2:"Flying",},
{id:"285", name:"Shroomish", type:"Grass", type2:"None",},
{id:"286", name:"Breloom", type:"Grass", type2:"Fighting",},
{id:"287", name:"Slakoth", type:"Normal", type2:"None",},
{id:"288", name:"Vigoroth", type:"Normal", type2:"None",},
{id:"289", name:"Slaking", type:"Normal", type2:"None",},
{id:"290", name:"Nincada", type:"Bug", type2:"Ground",},
{id:"291", name:"Ninjask", type:"Bug", type2:"Flying",},
{id:"292", name:"Shedinja", type:"Bug", type2:"Ghost",},
{id:"293", name:"Whismur", type:"Normal", type2:"None",},
{id:"294", name:"Loudred", type:"Normal", type2:"None",},
{id:"295", name:"Exploud", type:"Normal", type2:"None",},
{id:"296", name:"Makuhita", type:"Fighting", type2:"None",},
{id:"297", name:"Hariyama", type:"Fighting", type2:"None",},
{id:"298", name:"Azurill", type:"Normal", type2:"Fairy",},
{id:"299", name:"Nosepass", type:"Rock", type2:"None",},
{id:"300", name:"Skitty", type:"Normal", type2:"None",},
{id:"301", name:"Delcatty", type:"Normal", type2:"None",},
{id:"302", name:"Sableye", type:"Dark", type2:"Ghost",},
{id:"303", name:"Mawile", type:"Steel", type2:"Fairy",},
{id:"304", name:"Aron", type:"Steel", type2:"Rock",},
{id:"305", name:"Lairon", type:"Steel", type2:"Rock",},
{id:"306", name:"Aggron", type:"Steel", type2:"Rock",},
{id:"307", name:"Meditite", type:"Fighting", type2:"Psychic",},
{id:"308", name:"Medicham", type:"Fighting", type2:"Psychic",},
{id:"309", name:"Electrike", type:"Electric", type2:"None",},
{id:"310", name:"Manectric", type:"Electric", type2:"None",},
{id:"311", name:"Plusle", type:"Electric", type2:"None",},
{id:"312", name:"Minun", type:"Electric", type2:"None",},
{id:"313", name:"Volbeat", type:"Bug", type2:"None",},
{id:"314", name:"Illumise", type:"Bug", type2:"None",},
{id:"315", name:"Roselia", type:"Grass", type2:"Poison",},
{id:"316", name:"Gulpin", type:"Poison", type2:"None",},
{id:"317", name:"Swalot", type:"Poison", type2:"None",},
{id:"318", name:"Carvanha", type:"Water", type2:"Dark",},
{id:"319", name:"Sharpedo", type:"Water", type2:"Dark",},
{id:"320", name:"Wailmer", type:"Water", type2:"None",},
{id:"321", name:"Wailord", type:"Water", type2:"None",},
{id:"322", name:"Numel", type:"Fire", type2:"Ground",},
{id:"323", name:"Camerupt", type:"Fire", type2:"Ground",},
{id:"324", name:"Torkoal", type:"Fire", type2:"None",},
{id:"325", name:"Spoink", type:"Psychic", type2:"None",},
{id:"326", name:"Grumpig", type:"Psychic", type2:"None",},
{id:"327", name:"Spinda", type:"Normal", type2:"None",},
{id:"328", name:"Trapinch", type:"Ground", type2:"None",},
{id:"329", name:"Vibrava", type:"Ground", type2:"Dragon",},
{id:"330", name:"Flygon", type:"Ground", type2:"Dragon",},
{id:"331", name:"Cacnea", type:"Grass", type2:"None",},
{id:"332", name:"Cacturne", type:"Grass", type2:"Dark",},
{id:"333", name:"Swablu", type:"Normal", type2:"Flying",},
{id:"334", name:"Altaria", type:"Dragon", type2:"Flying",},
{id:"335", name:"Zangoose", type:"Normal", type2:"None",},
{id:"336", name:"Seviper", type:"Poison", type2:"None",},
{id:"337", name:"Lunatone", type:"Rock", type2:"Psychic",},
{id:"338", name:"Solrock", type:"Rock", type2:"Psychic",},
{id:"339", name:"Barboach", type:"Water", type2:"Ground",},
{id:"340", name:"Whiscash", type:"Water", type2:"Ground",},
{id:"341", name:"Corphish", type:"Water", type2:"None",},
{id:"342", name:"Crawdaunt", type:"Water", type2:"Dark",},
{id:"343", name:"Baltoy", type:"Ground", type2:"Psychic",},
{id:"344", name:"Claydol", type:"Ground", type2:"Psychic",},
{id:"345", name:"Lileep", type:"Rock", type2:"Grass",},
{id:"346", name:"Cradily", type:"Rock", type2:"Grass",},
{id:"347", name:"Anorith", type:"Rock", type2:"Bug",},
{id:"348", name:"Armaldo", type:"Rock", type2:"Bug",},
{id:"349", name:"Feebas", type:"Water", type2:"None",},
{id:"350", name:"Milotic", type:"Water", type2:"None",},
{id:"351", name:"Castform", type:"Normal", type2:"None",},
{id:"352", name:"Kecleon", type:"Normal", type2:"None",},
{id:"353", name:"Shuppet", type:"Ghost", type2:"None",},
{id:"354", name:"Banette", type:"Ghost", type2:"None",},
{id:"355", name:"Duskull", type:"Ghost", type2:"None",},
{id:"356", name:"Dusclops", type:"Ghost", type2:"None",},
{id:"357", name:"Tropius", type:"Grass", type2:"Flying",},
{id:"358", name:"Chimecho", type:"Psychic", type2:"None",},
{id:"359", name:"Absol", type:"Dark", type2:"None",},
{id:"360", name:"Wynaut", type:"Psychic", type2:"None",},
{id:"361", name:"Snorunt", type:"Ice", type2:"None",},
{id:"362", name:"Glalie", type:"Ice", type2:"None",},
{id:"363", name:"Spheal", type:"Ice", type2:"Water",},
{id:"364", name:"Sealeo", type:"Ice", type2:"Water",},
{id:"365", name:"Walrein", type:"Ice", type2:"Water",},
{id:"366", name:"Clamperl", type:"Water", type2:"None",},
{id:"367", name:"Huntail", type:"Water", type2:"None",},
{id:"368", name:"Gorebyss", type:"Water", type2:"None",},
{id:"369", name:"Relicanth", type:"Water", type2:"Rock",},
{id:"370", name:"Luvdisc", type:"Water", type2:"None",},
{id:"371", name:"Bagon", type:"Dragon", type2:"None",},
{id:"372", name:"Shelgon", type:"Dragon", type2:"None",},
{id:"373", name:"Salamence", type:"Dragon", type2:"Flying",},
{id:"374", name:"Beldum", type:"Steel", type2:"Psychic",},
{id:"375", name:"Metang", type:"Steel", type2:"Psychic",},
{id:"376", name:"Metagross", type:"Steel", type2:"Psychic",},
{id:"377", name:"Regirock", type:"Rock", type2:"None",},
{id:"378", name:"Regice", type:"Ice", type2:"None",},
{id:"379", name:"Registeel", type:"Steel", type2:"None",},
{id:"380", name:"Latias", type:"Dragon", type2:"Psychic",},
{id:"381", name:"Latios", type:"Dragon", type2:"Psychic",},
{id:"382", name:"Kyogre", type:"Water", type2:"None",},
{id:"383", name:"Groudon", type:"Ground", type2:"None",},
{id:"384", name:"Rayquaza", type:"Dragon", type2:"Flying",},
{id:"385", name:"Jirachi", type:"Steel", type2:"Psychic",},
{id:"386", name:"Deoxys", type:"Psychic", type2:"None",},
{id:"387", name:"Turtwig", type:"Grass", type2:"None",},
{id:"388", name:"Grotle", type:"Grass", type2:"None",},
{id:"389", name:"Torterra", type:"Grass", type2:"Ground",},
{id:"390", name:"Chimchar", type:"Fire", type2:"None",},
{id:"391", name:"Monferno", type:"Fire", type2:"Fighting",},
{id:"392", name:"Infernape", type:"Fire", type2:"Fighting",},
{id:"393", name:"Piplup", type:"Water", type2:"None",},
{id:"394", name:"Prinplup", type:"Water", type2:"None",},
{id:"395", name:"Empoleon", type:"Water", type2:"Steel",},
{id:"396", name:"Starly", type:"Normal", type2:"Flying",},
{id:"397", name:"Staravia", type:"Normal", type2:"Flying",},
{id:"398", name:"Staraptor", type:"Normal", type2:"Flying",},
{id:"399", name:"Bidoof", type:"Normal", type2:"None",},
{id:"400", name:"Bibarel", type:"Normal", type2:"Water",},
{id:"401", name:"Kricketot", type:"Bug", type2:"None",},
{id:"402", name:"Kricketune", type:"Bug", type2:"None",},
{id:"403", name:"Shinx", type:"Electric", type2:"None",},
{id:"404", name:"Luxio", type:"Electric", type2:"None",},
{id:"405", name:"Luxray", type:"Electric", type2:"None",},
{id:"406", name:"Budew", type:"Grass", type2:"Poison",},
{id:"407", name:"Roserade", type:"Grass", type2:"Poison",},
{id:"408", name:"Cranidos", type:"Rock", type2:"None",},
{id:"409", name:"Rampardos", type:"Rock", type2:"None",},
{id:"410", name:"Shieldon", type:"Rock", type2:"Steel",},
{id:"411", name:"Bastiodon", type:"Rock", type2:"Steel",},
{id:"412", name:"Burmy", type:"Bug", type2:"None",},
{id:"413", name:"Wormadam", type:"Bug", type2:"Grass",},
{id:"414", name:"Mothim", type:"Bug", type2:"Flying",},
{id:"415", name:"Combee", type:"Bug", type2:"Flying",},
{id:"416", name:"Vespiquen", type:"Bug", type2:"Flying",},
{id:"417", name:"Pachirisu", type:"Electric", type2:"None",},
{id:"418", name:"Buizel", type:"Water", type2:"None",},
{id:"419", name:"Floatzel", type:"Water", type2:"None",},
{id:"420", name:"Cherubi", type:"Grass", type2:"None",},
{id:"421", name:"Cherrim", type:"Grass", type2:"None",},
{id:"422", name:"Shellos", type:"Water", type2:"None",},
{id:"423", name:"Gastrodon", type:"Water", type2:"Ground",},
{id:"424", name:"Ambipom", type:"Normal", type2:"None",},
{id:"425", name:"Drifloon", type:"Ghost", type2:"Flying",},
{id:"426", name:"Drifblim", type:"Ghost", type2:"Flying",},
{id:"427", name:"Buneary", type:"Normal", type2:"None",},
{id:"428", name:"Lopunny", type:"Normal", type2:"None",},
{id:"429", name:"Mismagius", type:"Ghost", type2:"None",},
{id:"430", name:"Honchkrow", type:"Dark", type2:"Flying",},
{id:"431", name:"Glameow", type:"Normal", type2:"None",},
{id:"432", name:"Purugly", type:"Normal", type2:"None",},
{id:"433", name:"Chingling", type:"Psychic", type2:"None",},
{id:"434", name:"Stunky", type:"Poison", type2:"Dark",},
{id:"435", name:"Skuntank", type:"Poison", type2:"Dark",},
{id:"436", name:"Bronzor", type:"Steel", type2:"Psychic",},
{id:"437", name:"Bronzong", type:"Steel", type2:"Psychic",},
{id:"438", name:"Bonsly", type:"Rock", type2:"None",},
{id:"439", name:"Mime Jr.", type:"Psychic", type2:"Fairy",},
{id:"440", name:"Happiny", type:"Normal", type2:"None",},
{id:"441", name:"Chatot", type:"Normal", type2:"Flying",},
{id:"442", name:"Spiritomb", type:"Ghost", type2:"Dark",},
{id:"443", name:"Gible", type:"Dragon", type2:"Ground",},
{id:"444", name:"Gabite", type:"Dragon", type2:"Ground",},
{id:"445", name:"Garchomp", type:"Dragon", type2:"Ground",},
{id:"446", name:"Munchlax", type:"Normal", type2:"None",},
{id:"447", name:"Riolu", type:"Fighting", type2:"None",},
{id:"448", name:"Lucario", type:"Fighting", type2:"Steel",},
{id:"449", name:"Hippopotas", type:"Ground", type2:"None",},
{id:"450", name:"Hippowdon", type:"Ground", type2:"None",},
{id:"451", name:"Skorupi", type:"Poison", type2:"Bug",},
{id:"452", name:"Drapion", type:"Poison", type2:"Dark",},
{id:"453", name:"Croagunk", type:"Poison", type2:"Fighting",},
{id:"454", name:"Toxicroak", type:"Poison", type2:"Fighting",},
{id:"455", name:"Carnivine", type:"Grass", type2:"None",},
{id:"456", name:"Finneon", type:"Water", type2:"None",},
{id:"457", name:"Lumineon", type:"Water", type2:"None",},
{id:"458", name:"Mantyke", type:"Water", type2:"Flying",},
{id:"459", name:"Snover", type:"Grass", type2:"Ice",},
{id:"460", name:"Abomasnow", type:"Grass", type2:"Ice",},
{id:"461", name:"Weavile", type:"Dark", type2:"Ice",},
{id:"462", name:"Magnezone", type:"Electric", type2:"Steel",},
{id:"463", name:"Lickilicky", type:"Normal", type2:"None",},
{id:"464", name:"Rhyperior", type:"Ground", type2:"Rock",},
{id:"465", name:"Tangrowth", type:"Grass", type2:"None",},
{id:"466", name:"Electivire", type:"Electric", type2:"None",},
{id:"467", name:"Magmortar", type:"Fire", type2:"None",},
{id:"468", name:"Togekiss", type:"Fairy", type2:"Flying",},
{id:"469", name:"Yanmega", type:"Bug", type2:"Flying",},
{id:"470", name:"Leafeon", type:"Grass", type2:"None",},
{id:"471", name:"Glaceon", type:"Ice", type2:"None",},
{id:"472", name:"Gliscor", type:"Ground", type2:"Flying",},
{id:"473", name:"Mamoswine", type:"Ice", type2:"Ground",},
{id:"474", name:"Porygon-Z", type:"Normal", type2:"None",},
{id:"475", name:"Gallade", type:"Psychic", type2:"Fighting",},
{id:"476", name:"Probopass", type:"Rock", type2:"Steel",},
{id:"477", name:"Dusknoir", type:"Ghost", type2:"None",},
{id:"478", name:"Froslass", type:"Ice", type2:"Ghost",},
{id:"479", name:"Rotom", type:"Electric", type2:"Ghost",},
{id:"480", name:"Uxie", type:"Psychic", type2:"None",},
{id:"481", name:"Mesprit", type:"Psychic", type2:"None",},
{id:"482", name:"Azelf", type:"Psychic", type2:"None",},
{id:"483", name:"Dialga", type:"Steel", type2:"Dragon",},
{id:"484", name:"Palkia", type:"Water", type2:"Dragon",},
{id:"485", name:"Heatran", type:"Fire", type2:"Steel",},
{id:"486", name:"Regigigas", type:"Normal", type2:"None",},
{id:"487", name:"Giratina", type:"Ghost", type2:"Dragon",},
{id:"488", name:"Cresselia", type:"Psychic", type2:"None",},
{id:"489", name:"Phione", type:"Water", type2:"None",},
{id:"490", name:"Manaphy", type:"Water", type2:"None",},
{id:"491", name:"Darkrai", type:"Dark", type2:"None",},
{id:"492", name:"Shaymin", type:"Grass", type2:"Flying",},
{id:"493", name:"Arceus", type:"Normal", type2:"None",},
{id:"494", name:"Victini", type:"Psychic", type2:"Fire",},
{id:"495", name:"Snivy", type:"Grass", type2:"None",},
{id:"496", name:"Servine", type:"Grass", type2:"None",},
{id:"497", name:"Serperior", type:"Grass", type2:"None",},
{id:"498", name:"Tepig", type:"Fire", type2:"None",},
{id:"499", name:"Pignite", type:"Fire", type2:"Fighting",},
{id:"500", name:"Emboar", type:"Fire", type2:"Fighting",},
{id:"501", name:"Oshawott", type:"Water", type2:"None",},
{id:"502", name:"Dewott", type:"Water", type2:"None",},
{id:"503", name:"Samurott", type:"Water", type2:"None",},
{id:"504", name:"Patrat", type:"Normal", type2:"None",},
{id:"505", name:"Watchog", type:"Normal", type2:"None",},
{id:"506", name:"Lillipup", type:"Normal", type2:"None",},
{id:"507", name:"Herdier", type:"Normal", type2:"None",},
{id:"508", name:"Stoutland", type:"Normal", type2:"None",},
{id:"509", name:"Purrloin", type:"Dark", type2:"None",},
{id:"510", name:"Liepard", type:"Dark", type2:"None",},
{id:"511", name:"Pansage", type:"Grass", type2:"None",},
{id:"512", name:"Simisage", type:"Grass", type2:"None",},
{id:"513", name:"Pansear", type:"Fire", type2:"None",},
{id:"514", name:"Simisear", type:"Fire", type2:"None",},
{id:"515", name:"Panpour", type:"Water", type2:"None",},
{id:"516", name:"Simipour", type:"Water", type2:"None",},
{id:"517", name:"Munna", type:"Psychic", type2:"None",},
{id:"518", name:"Musharna", type:"Psychic", type2:"None",},
{id:"519", name:"Pidove", type:"Normal", type2:"Flying",},
{id:"520", name:"Tranquill", type:"Normal", type2:"Flying",},
{id:"521", name:"Unfezant", type:"Normal", type2:"Flying",},
{id:"522", name:"Blitzle", type:"Electric", type2:"None",},
{id:"523", name:"Zebstrika", type:"Electric", type2:"None",},
{id:"524", name:"Roggenrola", type:"Rock", type2:"None",},
{id:"525", name:"Boldore", type:"Rock", type2:"None",},
{id:"526", name:"Gigalith", type:"Rock", type2:"None",},
{id:"527", name:"Woobat", type:"Psychic", type2:"Flying",},
{id:"528", name:"Swoobat", type:"Psychic", type2:"Flying",},
{id:"529", name:"Drilbur", type:"Ground", type2:"None",},
{id:"530", name:"Excadrill", type:"Ground", type2:"Steel",},
{id:"531", name:"Audino", type:"Normal", type2:"None",},
{id:"532", name:"Timburr", type:"Fighting", type2:"None",},
{id:"533", name:"Gurdurr", type:"Fighting", type2:"None",},
{id:"534", name:"Conkeldurr", type:"Fighting", type2:"None",},
{id:"535", name:"Tympole", type:"Water", type2:"None",},
{id:"536", name:"Palpitoad", type:"Water", type2:"Ground",},
{id:"537", name:"Seismitoad", type:"Water", type2:"Ground",},
{id:"538", name:"Throh", type:"Fighting", type2:"None",},
{id:"539", name:"Sawk", type:"Fighting", type2:"None",},
{id:"540", name:"Sewaddle", type:"Bug", type2:"Grass",},
{id:"541", name:"Swadloon", type:"Bug", type2:"Grass",},
{id:"542", name:"Leavanny", type:"Bug", type2:"Grass",},
{id:"543", name:"Venipede", type:"Bug", type2:"Poison",},
{id:"544", name:"Whirlipede", type:"Bug", type2:"Poison",},
{id:"545", name:"Scolipede", type:"Bug", type2:"Poison",},
{id:"546", name:"Cottonee", type:"Grass", type2:"Fairy",},
{id:"547", name:"Whimsicott", type:"Grass", type2:"Fairy",},
{id:"548", name:"Petilil", type:"Grass", type2:"None",},
{id:"549", name:"Lilligant", type:"Grass", type2:"None",},
{id:"550", name:"Basculin", type:"Water", type2:"None",},
{id:"551", name:"Sandile", type:"Ground", type2:"Dark",},
{id:"552", name:"Krokorok", type:"Ground", type2:"Dark",},
{id:"553", name:"Krookodile", type:"Ground", type2:"Dark",},
{id:"554", name:"Darumaka", type:"Fire", type2:"None",},
{id:"555", name:"Darmanitan", type:"Fire", type2:"None",},
{id:"556", name:"Maractus", type:"Grass", type2:"None",},
{id:"557", name:"Dwebble", type:"Bug", type2:"Rock",},
{id:"558", name:"Crustle", type:"Bug", type2:"Rock",},
{id:"559", name:"Scraggy", type:"Dark", type2:"Fighting",},
{id:"560", name:"Scrafty", type:"Dark", type2:"Fighting",},
{id:"561", name:"Sigilyph", type:"Psychic", type2:"Flying",},
{id:"562", name:"Yamask", type:"Ghost", type2:"None",},
{id:"563", name:"Cofagrigus", type:"Ghost", type2:"None",},
{id:"564", name:"Tirtouga", type:"Water", type2:"Rock",},
{id:"565", name:"Carracosta", type:"Water", type2:"Rock",},
{id:"566", name:"Archen", type:"Rock", type2:"Flying",},
{id:"567", name:"Archeops", type:"Rock", type2:"Flying",},
{id:"568", name:"Trubbish", type:"Poison", type2:"None",},
{id:"569", name:"Garbodor", type:"Poison", type2:"None",},
{id:"570", name:"Zorua", type:"Dark", type2:"None",},
{id:"571", name:"Zoroark", type:"Dark", type2:"None",},
{id:"572", name:"Minccino", type:"Normal", type2:"None",},
{id:"573", name:"Cinccino", type:"Normal", type2:"None",},
{id:"574", name:"Gothita", type:"Psychic", type2:"None",},
{id:"575", name:"Gothorita", type:"Psychic", type2:"None",},
{id:"576", name:"Gothitelle", type:"Psychic", type2:"None",},
{id:"577", name:"Solosis", type:"Psychic", type2:"None",},
{id:"578", name:"Duosion", type:"Psychic", type2:"None",},
{id:"579", name:"Reuniclus", type:"Psychic", type2:"None",},
{id:"580", name:"Ducklett", type:"Water", type2:"Flying",},
{id:"581", name:"Swanna", type:"Water", type2:"Flying",},
{id:"582", name:"Vanillite", type:"Ice", type2:"None",},
{id:"583", name:"Vanillish", type:"Ice", type2:"None",},
{id:"584", name:"Vanilluxe", type:"Ice", type2:"None",},
{id:"585", name:"Deerling", type:"Normal", type2:"Grass",},
{id:"586", name:"Sawsbuck", type:"Normal", type2:"Grass",},
{id:"587", name:"Emolga", type:"Electric", type2:"Flying",},
{id:"588", name:"Karrablast", type:"Bug", type2:"None",},
{id:"589", name:"Escavalier", type:"Bug", type2:"Steel",},
{id:"590", name:"Foongus", type:"Grass", type2:"Poison",},
{id:"591", name:"Amoonguss", type:"Grass", type2:"Poison",},
{id:"592", name:"Frillish", type:"Water", type2:"Ghost",},
{id:"593", name:"Jellicent", type:"Water", type2:"Ghost",},
{id:"594", name:"Alomomola", type:"Water", type2:"None",},
{id:"595", name:"Joltik", type:"Bug", type2:"Electric",},
{id:"596", name:"Galvantula", type:"Bug", type2:"Electric",},
{id:"597", name:"Ferroseed", type:"Grass", type2:"Steel",},
{id:"598", name:"Ferrothorn", type:"Grass", type2:"Steel",},
{id:"599", name:"Klink", type:"Steel", type2:"None",},
{id:"600", name:"Klang", type:"Steel", type2:"None",},
{id:"601", name:"Klinklang", type:"Steel", type2:"None",},
{id:"602", name:"Tynamo", type:"Electric", type2:"None",},
{id:"603", name:"Eelektrik", type:"Electric", type2:"None",},
{id:"604", name:"Eelektross", type:"Electric", type2:"None",},
{id:"605", name:"Elgyem", type:"Psychic", type2:"None",},
{id:"606", name:"Beheeyem", type:"Psychic", type2:"None",},
{id:"607", name:"Litwick", type:"Ghost", type2:"Fire",},
{id:"608", name:"Lampent", type:"Ghost", type2:"Fire",},
{id:"609", name:"Chandelure", type:"Ghost", type2:"Fire",},
{id:"610", name:"Axew", type:"Dragon", type2:"None",},
{id:"611", name:"Fraxure", type:"Dragon", type2:"None",},
{id:"612", name:"Haxorus", type:"Dragon", type2:"None",},
{id:"613", name:"Cubchoo", type:"Ice", type2:"None",},
{id:"614", name:"Beartic", type:"Ice", type2:"None",},
{id:"615", name:"Cryogonal", type:"Ice", type2:"None",},
{id:"616", name:"Shelmet", type:"Bug", type2:"None",},
{id:"617", name:"Accelgor", type:"Bug", type2:"None",},
{id:"618", name:"Stunfisk", type:"Ground", type2:"Electric",},
{id:"619", name:"Mienfoo", type:"Fighting", type2:"None",},
{id:"620", name:"Mienshao", type:"Fighting", type2:"None",},
{id:"621", name:"Druddigon", type:"Dragon", type2:"None",},
{id:"622", name:"Golett", type:"Ground", type2:"Ghost",},
{id:"623", name:"Golurk", type:"Ground", type2:"Ghost",},
{id:"624", name:"Pawniard", type:"Dark", type2:"Steel",},
{id:"625", name:"Bisharp", type:"Dark", type2:"Steel",},
{id:"626", name:"Bouffalant", type:"Normal", type2:"None",},
{id:"627", name:"Rufflet", type:"Normal", type2:"Flying",},
{id:"628", name:"Braviary", type:"Normal", type2:"Flying",},
{id:"629", name:"Vullaby", type:"Dark", type2:"Flying",},
{id:"630", name:"Mandibuzz", type:"Dark", type2:"Flying",},
{id:"631", name:"Heatmor", type:"Fire", type2:"None",},
{id:"632", name:"Durant", type:"Bug", type2:"Steel",},
{id:"633", name:"Deino", type:"Dark", type2:"Dragon",},
{id:"634", name:"Zweilous", type:"Dark", type2:"Dragon",},
{id:"635", name:"Hydreigon", type:"Dark", type2:"Dragon",},
{id:"636", name:"Larvesta", type:"Bug", type2:"Fire",},
{id:"637", name:"Volcarona", type:"Bug", type2:"Fire",},
{id:"638", name:"Cobalion", type:"Steel", type2:"Fighting",},
{id:"639", name:"Terrakion", type:"Rock", type2:"Fighting",},
{id:"640", name:"Virizion", type:"Grass", type2:"Fighting",},
{id:"641", name:"Tornadus", type:"Flying", type2:"None",},
{id:"642", name:"Thundurus", type:"Electric", type2:"Flying",},
{id:"643", name:"Reshiram", type:"Dragon", type2:"Fire",},
{id:"644", name:"Zekrom", type:"Dragon", type2:"Electric",},
{id:"645", name:"Landorus", type:"Ground", type2:"Flying",},
{id:"646", name:"Kyurem", type:"Dragon", type2:"Ice",},
{id:"647", name:"Keldeo", type:"Water", type2:"Fighting",},
{id:"648", name:"Meloetta", type:"Normal", type2:"Psychic",},
{id:"649", name:"Genesect", type:"Bug", type2:"Steel",},
{id:"650", name:"Chespin", type:"Grass", type2:"None",},
{id:"651", name:"Quilladin", type:"Grass", type2:"None",},
{id:"652", name:"Chesnaught", type:"Grass", type2:"Fighting",},
{id:"653", name:"Fennekin", type:"Fire", type2:"None",},
{id:"654", name:"Braixen", type:"Fire", type2:"None",},
{id:"655", name:"Delphox", type:"Fire", type2:"Psychic",},
{id:"656", name:"Froakie", type:"Water", type2:"None",},
{id:"657", name:"Frogadier", type:"Water", type2:"None",},
{id:"658", name:"Greninja", type:"Water", type2:"Dark",},
{id:"659", name:"Bunnelby", type:"Normal", type2:"None",},
{id:"660", name:"Diggersby", type:"Normal", type2:"Ground",},
{id:"661", name:"Fletchling", type:"Normal", type2:"Flying",},
{id:"662", name:"Fletchinder", type:"Fire", type2:"Flying",},
{id:"663", name:"Talonflame", type:"Fire", type2:"Flying",},
{id:"664", name:"Scatterbug", type:"Bug", type2:"None",},
{id:"665", name:"Spewpa", type:"Bug", type2:"None",},
{id:"666", name:"Vivillon", type:"Bug", type2:"Flying",},
{id:"667", name:"Litleo", type:"Fire", type2:"Normal",},
{id:"668", name:"Pyroar", type:"Fire", type2:"Normal",},
{id:"669", name:"Flabebe", type:"Fairy", type2:"None",},
{id:"670", name:"Floette", type:"Fairy", type2:"None",},
{id:"671", name:"Florges", type:"Fairy", type2:"None",},
{id:"672", name:"Skiddo", type:"Grass", type2:"None",},
{id:"673", name:"Gogoat", type:"Grass", type2:"None",},
{id:"674", name:"Pancham", type:"Fighting", type2:"None",},
{id:"675", name:"Pangoro", type:"Fighting", type2:"Dark",},
{id:"676", name:"Furfrou", type:"Normal", type2:"None",},
{id:"677", name:"Espurr", type:"Psychic", type2:"None",},
{id:"678", name:"Meowstic", type:"Psychic", type2:"None",},
{id:"679", name:"Honedge", type:"Steel", type2:"Ghost",},
{id:"680", name:"Doublade", type:"Steel", type2:"Ghost",},
{id:"681", name:"Aegislash", type:"Steel", type2:"Ghost",},
{id:"682", name:"Spritzee", type:"Fairy", type2:"None",},
{id:"683", name:"Aromatisse", type:"Fairy", type2:"None",},
{id:"684", name:"Swirlix", type:"Fairy", type2:"None",},
{id:"685", name:"Slurpuff", type:"Fairy", type2:"None",},
{id:"686", name:"Inkay", type:"Dark", type2:"Psychic",},
{id:"687", name:"Malamar", type:"Dark", type2:"Psychic",},
{id:"688", name:"Binacle", type:"Rock", type2:"Water",},
{id:"689", name:"Barbaracle", type:"Rock", type2:"Water",},
{id:"690", name:"Skrelp", type:"Poison", type2:"Water",},
{id:"691", name:"Dragalge", type:"Poison", type2:"Dragon",},
{id:"692", name:"Clauncher", type:"Water", type2:"None",},
{id:"693", name:"Clawitzer", type:"Water", type2:"None",},
{id:"694", name:"Helioptile", type:"Electric", type2:"Normal",},
{id:"695", name:"Heliolisk", type:"Electric", type2:"Normal",},
{id:"696", name:"Tyrunt", type:"Rock", type2:"Dragon",},
{id:"697", name:"Tyrantrum", type:"Rock", type2:"Dragon",},
{id:"698", name:"Amaura", type:"Rock", type2:"Ice",},
{id:"699", name:"Aurorus", type:"Rock", type2:"Ice",},
{id:"700", name:"Sylveon", type:"Fairy", type2:"None",},
{id:"701", name:"Hawlucha", type:"Fighting", type2:"Flying",},
{id:"702", name:"Dedenne", type:"Electric", type2:"Fairy",},
{id:"703", name:"Carbink", type:"Rock", type2:"Fairy",},
{id:"704", name:"Goomy", type:"Dragon", type2:"None",},
{id:"705", name:"Sliggoo", type:"Dragon", type2:"None",},
{id:"706", name:"Goodra", type:"Dragon", type2:"None",},
{id:"707", name:"Klefki", type:"Steel", type2:"Fairy",},
{id:"708", name:"Phantump", type:"Ghost", type2:"Grass",},
{id:"709", name:"Trevenant", type:"Ghost", type2:"Grass",},
{id:"710", name:"Pumpkaboo", type:"Ghost", type2:"Grass",},
{id:"711", name:"Gourgeist", type:"Ghost", type2:"Grass",},
{id:"712", name:"Bergmite", type:"Ice", type2:"None",},
{id:"713", name:"Avalugg", type:"Ice", type2:"None",},
{id:"714", name:"Noibat", type:"Dragon", type2:"None",},
{id:"715", name:"Noivern", type:"Dragon", type2:"None",},
{id:"716", name:"Xerneas", type:"Fairy", type2:"None",},
{id:"717", name:"Yveltal", type:"Dark", type2:"Flying",},
{id:"718", name:"Zygarde", type:"Dragon", type2:"Ground",},
{id:"719", name:"Diancie", type:"Rock", type2:"Fairy",},
{id:"720", name:"Hoopa", type:"Psychic", type2:"Ghost",},
{id:"721", name:"Volcanion", type:"Fire", type2:"Water",},
];

function createPreloadedImages(){
    var url = '';
    var html = "";
    for (var i = 0; i < pokemonList.length; i++){
        var pokemonPosition = pokemonList[i].id;
        url = 'images/' + pokemonPosition + '.gif';
        var preloadTest = preloadImage(url);
        preloadTest.onload = function(){
            html = 'Preloading all images: ' + i + '/' + (pokemonList.length - 1);
         };

        document.getElementById("pokemonCatchInfo").innerHTML = html;
        if (i === pokemonList.length - 1) {
            html = 'Done loading all images';
        };
    };
    document.getElementById("pokemonCatchInfo").innerHTML = html;
};
createPreloadedImages();

function preloadImage(url) {
    var img = new Image();
    img.src = url;
    return img;
};

var caughtPokemon = [];
var player = {
	caught:{
	fire: 0,
	water: 0,
	grass: 0,
	electric: 0,
	normal: 0,
	psychic: 0,
	dragon: 0,
	ghost: 0,
	rock: 0,
	ground: 0,
	poison: 0,
	fighting: 0,
	flying: 0,
	bug: 0,
	ice: 0,
	},
	maxType:{
	fireMax: 0,
	waterMax: 0,
	grassMax: 0,
	electricMax: 0,
	normalMax: 0,
	psychicMax: 0,
	dragonMax: 0,
	ghostMax: 0,
	rockMax: 0,
	groundMax: 0,
	poisonMax: 0,
	fightingMax: 0,
	flyingMax: 0,
	bugMax: 0,
	iceMax: 0,
	}
};
function getAllPokemonTypes(){
	for (var i = 0; i < pokemonList.length; i++){
		var type = pokemonList[i].type + "Max";
		player.maxType[type] += 1;
	};
};
getAllPokemonTypes();
function getPokemon(){
	var html ="";
	if (pokemonList.length > 0){
	var randomPokemon = pokemonList[Math.floor(Math.random()*pokemonList.length)];
	var index = pokemonList.indexOf(randomPokemon);
	var pokemonPosition = randomPokemon.id
	html += '<div class="row">';
	html += '<div class="col-xs-4 col-xs-offset-4" style="height:200px;background-color:green;">';
	html += '<img src="images/' + pokemonPosition + '.gif" style="margin-top:50px; border:1px solid;">';
	html += '</div>';
	html += '</div>';
	html += '<div class="row">';
	html += '<div class="col-xs-4 col-xs-offset-4">';
	html += randomPokemon.id + " - " + randomPokemon.name + " - " + randomPokemon.type + " (Catch rate: "  + randomPokemon.chance + "%)";
	html += '<div class="row"><div class="col-xs-12">'
	html += '<button type="button" onclick="catchPokemon(' + index + ')">Catch it!</button>';
	html += '</div>';
	html += '<div class="col-xs-12">';
	html += '</div>';
	html += '</div>';
	html += '</div>';
	html += '</div>';
	}
	else{
	html += '<div class="col-xs-4 col-xs-offset-4">';
	html += "GAME FINISHED!";
	html += '</div>';
	}
	document.getElementById("pokemonDisplay").innerHTML = html;
};

function catchPokemon(index){
	var randomPokemon = pokemonList[index];
	var type = randomPokemon.type;
	var randomNumber = Math.floor(Math.random() * 100) + 1;
	var html = "";
	if (randomNumber <= randomPokemon.chance){
		player.caught[type] += 1;
		createPokemonInfo();
		html += "You caught " + randomPokemon.name;
		document.getElementById("pokemonCatchInfo").innerHTML = html;
		pokemonList.splice(index,1);
	}
	else{
		html += "You fail to catch " + randomPokemon.name;
		document.getElementById("pokemonCatchInfo").innerHTML = html;
	};
getPokemon();
};
getPokemon();

function createPokemonInfo(){
	var html ="";
	html += '<div class="col-xs-8 col-xs-offset-2">';
	for (var key in player.caught){
		var type = player.caught[key];
		var typeMax = key + "Max";
		var maxType = player.maxType[typeMax]
		html += key + " " + type + "/" + maxType + " | ";
	};
	html += '</div>';

	document.getElementById("pokemonInfo").innerHTML = html;
};
createPokemonInfo();
